theme="autumn_night"

[editor]
bufferline = "multiple"
line-number = "relative"
[editor.cursor-shape]
insert="bar"
[keys.normal]
";" = "command_mode"
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
tab = ":bn"
C-O = ":config-reload"
[keys.normal.space]
w = ":w"
q = ":bc"
[editor.soft-wrap]
enable = true
